### PR TITLE
Translation update (pt-br)

### PR DESCRIPTION
**Pull request by eduardomozart**
This pull request contains some translation updates.

### CODE REVIEW

**Comment by Klap-in** [comment]
Thanks! 
For information: did you know that you can also submit translations via https://translate.dokuwiki.org/?lang=pt-br

**Comment by eduardomozart** [comment]
Hello @Klap-in,
I've tried to send the translation from there but if you click on "Show settings" at the bottom (https://translate.dokuwiki.org/plugin/odt/settings) there's more than +3 erros for the ODT repo so translation aren't being synced to this repo anymore for some reason I don't know so my translation wasn't being sent as a PR.

**Comment by Klap-in** [comment]
Ah, good point. I will check what holds it back, and reset the tool.

**Comment by Klap-in** [comment]
I have fixed a git error and reset this plugin in the translation tool. Now your update is visible as well ;-)

**Pull request merged**
